import { Roboto } from "next/font/google";
import { Urbanist } from "next/font/google";
import "./globals.css";
import NavTest from "@/components/NavTest";
import Footer from "@/components/Footer";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "500", "700"],
});

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["100", "400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${urbanist.className}`}>
        <main className={` sm:max-w-[1280px] mx-auto  overflow-hidden `}>
          <div className="w-full sm:px-16 px-6">
            <NavTest />
            {children}
            <Footer />
          </div>
        </main>
      </body>
    </html>
  );
}
